version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: itq-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docuser
      POSTGRES_PASSWORD: docpass
      POSTGRES_DB: document_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
